### ISSUE TITLE
Same message received multiple times.

### ISSUE THREAD

**Issue by mfrlin** [wialon/gmqtt#120]
Currently if you subscribe to `path/+` and `path/subpath` on message callback will be triggered twice. 

Is this expected behaviour?

My personal opinion is it should not be.

**Comment by Mixser** [comment]
Hi @mfrlin, thanks for the question.
This is expected behavior - client will receive two independent packages from the server and client will process them separate.

**Comment by Lenka42** [comment]
Hi @mfrlin 
Number of messages you receive does not depend on the gmqtt library, but broker implementation. Which MQTT broker do you use?
Here is [MQTT specification](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901117): "When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.4-2]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case."

**Comment by mfrlin** [comment]
Thank you for explanation.

I'm using mosquitto btw.
