### ISSUE TITLE
MQTT 5.0 support

### ISSUE THREAD

**Issue by ashchurko** [wialon/gmqtt#2]
We need [MQTT 5.0 specification](http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs01/mqtt-v5.0-cs01.html) support, at least part of it. Let's make this library v5.0 compliant, here is the list of features we need in order of importance:

- [x] MQTT v5.0 CONNECT packet and custom properties per each packet

- [x] PUBLISH => set message expiry interval

Next are less important:
- [x] subscription identifier => client provides own index upon subscribe, broker specify subscription identifier that was the reason of message delivery

- [x] receive maximum => client specifies limit on quantity of inflight messages sent by broker

- [x] will delay interval

**Comment by NicoHood** [comment]
Hi, I just found your mqtt library for python!

It seems to be the first that supports mqtt5, which is nice. The list above seems a bit incomplete. Are you sure all other functions are also supported? You can possibly try out this test suite:
https://github.com/eclipse/paho.mqtt.testing

Another thing I am wondering about is how much you support of the following table:
https://www.eclipse.org/paho/downloads.php
I am asking because I was looking for persistent session support which the paho library seems to not support yet. Does your library support this and other features yet?

**Comment by wialon** [comment]
@NicoHood Hi, thank you for your interest.

We are using this lib for our [internal projects](https://flespi.com), so it can be incomplete. You can try it for your project and if you will find some mistakes or feature, which we are not supporting, feel free to PR or Issues. :slightly_smiling_face: 

We are curently working on persitent session suport and you can try it at #15.
