### ISSUE TITLE
Client does not fallback to MQTT3 on rabbitmq

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [wialon/gmqtt#45]
Hey,

From the readme I guessed that gmqtt should reconnect using protocol v3 if mqtt v5 is not supported on the broker side. I'm using rabbitmq which does not support v5. gmqtt got disconnected right after establishing the connected but never reconnected. When explicitly setting v3 it works smoothly. I don't think that's a bug but maybe the Readme should be modified to point out that automatic protocol version adaption is not always working.

Best regards

**Comment by Lenka42** [comment]
Hi, thanks for notice!
Probably this happened because RabbitMQ broker didn't use proper connect acknowledgement code. Good one is 
0x01 Connection Refused, unacceptable protocol version
Receiving this code, client will downgrade protocol version and try to reconnect. 
I will add more related logging and clarification in README

**Comment by HerrMuellerluedenscheid** [comment]
Not sure if it helps. This is the logging output from gmqtt:

```
INFO:gmqtt.mqtt.protocol:[CONNECTION MADE]
INFO:gmqtt.mqtt.protocol:[CONN CLOSE NORMALLY]
INFO:mqtt.MQTTClient:disconnected
```
and this is the logging from rabbitmq:
```
2019-06-04 16:58:27.499 [error] <0.3814.0> MQTT cannot parse frame for connection '[[MYIPADDRESS]]:37366 -> [[SERVERIPADDRESS]]:1883', unparseable payload: <<16,33,0,4,77,81,84,84,5,194,0,60,0,0,5 [...]
```

Feel free to close the topic. Just wanted to draw your attention to that one.
