### ISSUE TITLE
How to know publish is successful or failed when qos is 1 or 2 and how to retry it manually?

### ISSUE THREAD

**Issue by VinceWg** [wialon/gmqtt#78]
As the title says, I want to know that publish runs successfully or failed when the qos is set to 1 or 2, if successfully, record it, if failed, retry it manually. So what should I do please?

**Comment by Mixser** [comment]
Hi @VinceWg 

Currently *gmqtt* has no easy way to do it. But it's not imposible. 

If you just want to know when your qos1-2 message has not been delivered (we didn't receive PUBACK) you may to inherite from `gmqtt.storage.BasePersistentStorage` and implement you own storage of that messages. Than you must pass the instance of you storage to Client `__init__` method by kwargs `persistent_storage=you_storage_impl_instance`.

About manualy retry. This more complicated because this logic has been implemented in Client at `_resend_qos_messages` and no other way to configure this (only inherite and overwrite this method). Also you can implement logic about which messsage you need to resend in your storage implementation, but `messages` in storage will be in raw view (bytes).

**Comment by VinceWg** [comment]
@Mixser 
Thx much for your explain, it gives me a clear solution.
